# language type:
language: cpp

# compilator system:
compiler:
- clang
- gcc

os:
- linux
- osx

osx_image: xcode61

# previous actions:
before_script: 
  - rm -rf *
  - git clone https://github.com/HeeroYui/ewol.git
  - cd ewol; git checkout origin/dev -b dev; cd ..
  - cd ewol; git submodule init; cd ..
  - cd ewol; git submodule update; cd ..
  - cd ewol; git submodule foreach git checkout master; cd ..
  - cd ewol; git submodule foreach git pull; cd ..

#install Gcc to have lisstdc++ 4.8 & gcc 4.8
install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - sudo rm /usr/bin/gcc /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++

# build sequence with Lutin :
script: 
  - if [ "$CXX" == "clang++" ]; then ./ewol/build/lutin.py -C -P -cclang -mdebug -p ejson_test; fi
  - if [ "$CXX" == "g++" ]; then ./ewol/build/lutin.py -C -P -cgcc -mdebug -p ejson_test; fi

after_script:
  - if [ "$CXX" == "clang++" ]; then ./out/Linux_x86_64/debug/staging/clang/ejson_test/usr/bin/ejson_test; fi
  - if [ "$CXX" == "g++" ]; then ./out/Linux_x86_64/debug/staging/gcc/ejson_test/usr/bin/ejson_test; fi

#send e-mail on compilation result:
notifications:
  email:
    - yui.heero@gmail.com


