language: cpp

compiler:
- clang
- gcc

os:
- linux

before_script:
  - cd ..
  - git clone https://github.com/atria-soft/etk.git
  - git clone https://github.com/generic-library/gtest-lutin.git --recursive
  - pwd
  - ls -l
  - if [ "$CXX" == "clang++" ]; then BUILDER=clang; else BUILDER=gcc; fi

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++-4.9-dev
  - sudo apt-get install -qq g++-4.9
  - sudo rm /usr/bin/gcc /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-4.9 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++
  - sudo pip install lutin

script: 
  - lutin -C -P -c$BUILDER -mdebug -p ejson-test
  - ./out/Linux_x86_64/debug/staging/$BUILDER/ejson-test/usr/bin/ejson-test

notifications:
  email:
    - yui.heero@gmail.com
